# Prometheus Configuration for MATLAB Engine API Monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'matlab-engine-api'
    environment: 'production'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Scrape configuration
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # MATLAB Engine API metrics
  - job_name: 'matlab-engine-api'
    static_configs:
      - targets: ['matlab-engine-api:8000']
    scrape_interval: 15s
    metrics_path: '/metrics'
    scrape_timeout: 10s
    honor_labels: false
    honor_timestamps: true
    params:
      format: ['prometheus']

  # System metrics (if node_exporter is installed)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Docker container metrics (if cAdvisor is installed)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Redis metrics (if Redis is used)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # PostgreSQL metrics (if PostgreSQL is used)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

# Remote write configuration (for external monitoring services)
# remote_write:
#   - url: 'https://your-external-prometheus/api/v1/write'
#     basic_auth:
#       username: 'your-username'
#       password: 'your-password'

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true