name: MATLAB CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Run MATLAB Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023b
      
      - name: Run MATLAB build
        uses: matlab-actions/run-build@v2
        with:
          tasks: test
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
      
      - name: Upload code coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: code-coverage
          path: code-coverage/

  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023b
      
      - name: Run MATLAB build
        uses: matlab-actions/run-build@v2
        with:
          tasks: check

  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: [test, code-quality]
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023b
      
      - name: Generate documentation
        uses: matlab-actions/run-command@v2
        with:
          command: |
            set(0, 'DefaultFigureVisible', 'off');
            addpath(genpath('src'));
            addpath('examples');
            mkdir('docs/html');
            publish('run_all_demos', 'format', 'html', 'outputDir', 'docs/html', ...
                    'showCode', true, 'evalCode', false);
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html